language: python
python: '2.7'
env:
  global:
    - DB_DIR=dbdir
    #coveralls repo key
    - secure: lJtUySFLmLPV4csef2XQXqH5ZEMKK6sHkiKeIIFdq0oFUlBk4NA3xVaOnkduBXv0lRQIFp+Bsz/2bCz5YorvA2t8FRU3zjHZMNPMiRSCS95NekayXroDpJRa3nRn14w3xuT9nJ1SncfEsTiE8yKhcESbJQbcJl7nUOCluB+HU+E=
before_install:
  - pip uninstall -y coveralls || true
install:
  - pip install coverage
  - pip install coveralls
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pandas biopython numpy cython sqlalchemy'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install your own package into the environment
  - bash scripts/create_oncotator_venv.sh -e environment_exists_already -k
  - python setup.py install
script:
  - mkdir dbdir
  - sed -r "s:dbDir=MY_DB_DIR:dbDir=${DB_DIR}:g" test/configs/personal-test.config.template >test/configs/personal-test.config
  - nosetests --all-modules --exe --with-xunit --xunit-file=${PWD}/nosetests.xml -w test -v --with-coverage --cover-package=oncotator,test --cover-inclusive --cover-erase --cover-branches --cover-tests
  - oncotator --help
after_success: coveralls
