language: python
python: '2.7'
env:
  global:
    - DB_DIR=dbdir
    #coveralls repo key
    - secure: lJtUySFLmLPV4csef2XQXqH5ZEMKK6sHkiKeIIFdq0oFUlBk4NA3xVaOnkduBXv0lRQIFp+Bsz/2bCz5YorvA2t8FRU3zjHZMNPMiRSCS95NekayXroDpJRa3nRn14w3xuT9nJ1SncfEsTiE8yKhcESbJQbcJl7nUOCluB+HU+E=
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade python-nose
  - sudo apt-get upgrade python-coverage
install:
  # install deps
  - bash scripts/create_oncotator_venv.sh
  # install your own package into the environment
  - sudo python setup.py install
  - pip install coveralls
script:
  - mkdir dbdir
  - sed -r "s:dbDir=MY_DB_DIR:dbDir=${DB_DIR}:g" test/configs/personal-test.config.template >test/configs/personal-test.config
  - nosetests --all-modules --exe --with-xunit --xunit-file=${PWD}/nosetests.xml -w test -v --with-coverage --cover-package=oncotator,test --cover-inclusive --cover-erase --cover-branches --cover-tests
  - oncotator --help
after_success: coveralls
